import type { PhotoData, GalleryPhoto } from '@/types/image';
import { createGalleryPhoto } from './cloudinaryClient';

// Sample photo data for testing (using Cloudinary's sample images)
export const samplePhotos: PhotoData[] = [
  {
    publicId: 'samples/landscapes/beach-boat',
    title: 'Beach Boat',
    description: 'A peaceful boat scene at the beach',
    category: 'landscape',
    tags: ['beach', 'boat', 'ocean', 'peaceful'],
    width: 1600,
    height: 1067,
    aspectRatio: 1.5,
    createdAt: '2024-01-15T10:00:00Z',
    alt: 'A boat on a peaceful beach scene',
  },
  {
    publicId: 'samples/landscapes/nature-mountains',
    title: 'Mountain Vista',
    description: 'Majestic mountain landscape',
    category: 'landscape',
    tags: ['mountains', 'nature', 'vista', 'landscape'],
    width: 1600,
    height: 1200,
    aspectRatio: 1.33,
    createdAt: '2024-01-14T15:30:00Z',
    alt: 'Majestic mountain landscape vista',
  },
  {
    publicId: 'samples/animals/three-dogs',
    title: 'Three Dogs',
    description: 'Three adorable dogs sitting together',
    category: 'animals',
    tags: ['dogs', 'animals', 'pets', 'cute'],
    width: 1600,
    height: 1067,
    aspectRatio: 1.5,
    createdAt: '2024-01-13T12:00:00Z',
    alt: 'Three dogs sitting together',
  },
  {
    publicId: 'samples/food/spices',
    title: 'Colorful Spices',
    description: 'Beautiful arrangement of colorful spices',
    category: 'food',
    tags: ['spices', 'colorful', 'food', 'cooking'],
    width: 1600,
    height: 1200,
    aspectRatio: 1.33,
    createdAt: '2024-01-12T09:15:00Z',
    alt: 'Colorful spices arranged beautifully',
  },
  {
    publicId: 'samples/people/kitchen-bar',
    title: 'Kitchen Bar',
    description: 'Modern kitchen bar setup',
    category: 'interior',
    tags: ['kitchen', 'modern', 'interior', 'design'],
    width: 1600,
    height: 1067,
    aspectRatio: 1.5,
    createdAt: '2024-01-11T16:45:00Z',
    alt: 'Modern kitchen bar setup',
  },
  {
    publicId: 'samples/shoe',
    title: 'Vintage Shoe',
    description: 'Classic vintage shoe photography',
    category: 'objects',
    tags: ['shoe', 'vintage', 'classic', 'photography'],
    width: 1600,
    height: 1200,
    aspectRatio: 1.33,
    createdAt: '2024-01-10T14:20:00Z',
    alt: 'Classic vintage shoe',
  },
  {
    publicId: 'samples/cloudinary-icon',
    title: 'Cloudinary Icon',
    description: 'The iconic Cloudinary logo',
    category: 'graphics',
    tags: ['logo', 'cloudinary', 'icon', 'brand'],
    width: 1600,
    height: 1600,
    aspectRatio: 1.0,
    createdAt: '2024-01-09T11:00:00Z',
    alt: 'Cloudinary logo icon',
  },
  {
    publicId: 'samples/bike',
    title: 'Vintage Bicycle',
    description: 'A beautiful vintage bicycle',
    category: 'objects',
    tags: ['bicycle', 'vintage', 'transport', 'classic'],
    width: 1600,
    height: 1067,
    aspectRatio: 1.5,
    createdAt: '2024-01-08T13:30:00Z',
    alt: 'Beautiful vintage bicycle',
  },
];

// Convert sample photos to gallery photos with URLs
export const sampleGalleryPhotos: GalleryPhoto[] =
  samplePhotos.map(createGalleryPhoto);
